---
- hosts: file
  become: yes
  gather_facts: no
  vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "Sudo password"
    private: yes

  tasks:
          - name: create folder
            file:
                    path: "/app/etl"
                    state: directory
                    owner: username
                    group: group
