
---
- hosts: azure
  become: yes
  gather_facts: no
  vars_prompt:
          - name: "ansible_sudo_pass"
            prompt: "Enter Sudo Password"
            private: yes
  vars_files:
          - ~/vars/mountdata.yml

  tasks:
          - name: Execute script for extend mount
            script: extend_mount_point.sh "{{ device_name }}" "{{ mount_name }}"
            register: dfoutput

         # - name: Print extended mount
            # shell: df -h /home | tail -1
            # register: dfoutput

          - debug:
                  msg: "{{ dfoutput.stdout_lines }}"
