
---
        - hosts: sssd
          become: yes
          serial: 10
          gather_facts: yes
          vars_prompt:
          - name: "ansible_sudo_pass"
            prompt: "Sudo password"
            private: yes
          vars:
                - rhv:  ansible_distribution

          tasks:

#          - meta: end_play
#            when: ansible_distribution != "RedHat"

          - name: Take backup of sssd.conf file
            copy:
                src: /etc/sssd/sssd.conf
                dest: /etc/sssd/sssd.conf-{{ansible_date_time.iso8601_basic_short}}
                remote_src: yes

          - name: Copy new sssd.conf file
            copy:
                    src: sssd.conf
                    dest: /etc/sssd/
                    mode: '0600'

          - name: Update sssd.conf for HPC
            command: chdir=/etc/sssd/ {{ item }}
            with_items:
                    - sed -i '/services/a [nss]\noverride_homedir = /sc/kzd/home/%u' sssd.conf
                    - sed -i '/services/a \\' sssd.conf
            when: inventory_hostname.startswith('kzdlsc')

          - name: Provide local group access
            command: 'realm permit -g group1 -g group2 -g group3'
#            register: command_output

          - name: Delete sssd cache
            block:
            - name: Remove db file
              file:
                      state: absent
                      path: /var/lib/sss/db/

            - name: Create db file
              file:
                      path: /var/lib/sss/db
                      state: directory
                      owner: sssd
                      group: sssd
                      mode: 0700

          - name: Restart sssd service
            service:
                    name: sssd
                    state: restarted

          - name: Get realm output
            command: realm list
            register: cmd_opt

          - debug:
                 msg: "{{ cmd_opt.stdout_lines }}"
