---
- name: Remove VM from vCenter
  hosts: localhost
  gather_facts: no
  vars_files:
          - config.yaml
          - .secret_key
          - linux-gc-server.yaml
  tasks:

          
          - name: Remove virtual machine from inventory
            community.vmware.vmware_guest:
                    validate_certs: false
                    hostname: "{{ vmware_host }}"
                    username: "{{ vmware_user }}"
                    password: "{{ vmware_password }}"
                    name: "{{ vmware.name }}"
                    state: absent
                    force: True
