---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  vars_files:
          - config.yaml
          - .secret_key
          - linux-gc-server.yaml
  tasks:

  - set_fact:
      num_cpu_cores_per_socket: "{{ vmware.num_cpus | int/2 }}"

  - name: Clone the template
    vmware_guest:
      hostname: "{{ vmware_host }}"
      username: "{{ vmware_user }}"
      password: "{{ vmware_password }}"
      validate_certs: False
      name: "{{ vmware.name }}"
      template: rhel87-vm-gi-20230126
      datacenter: "Warsaw (WSP)"
      folder: /
      state: poweredoff
      cluster: "vcenter_cluster"
      # wait_for_ip_address: yes
      hardware:
        boot_firmware: efi
        memory_mb: "{{ vmware.memory_mb }}"
        num_cpus: "{{ vmware.num_cpus }}"
        num_cpu_cores_per_socket: "{{ num_cpu_cores_per_socket | int }}"
        #scsi: paravirtual
      networks:
      - name: "{{ vmware.port_group }}"
        start_connected: yes
           #mac: "{{ vmware.mac_address  }}"
           #ip: "{{ vmware.ip_address }}"
           #netmask: "{{ vmware.netmask }}"
        device_type: vmxnet3
        type: static
        #delegate_to: localhost
        #register: deploy_vm
        #throttle: 5

  - name: Poweron Virtual Machine
    vmware_guest:
            validate_certs: false
            hostname: "{{ vmware_host }}"
            username: "{{ vmware_user }}"
            password: "{{ vmware_password }}"
            name: "{{ vmware.name }}"
            state: poweredon
